# Generated by Django 4.2.13 on 2026-06-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('overview', models.TextField(blank=True)),
                ('work_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
                'ordering': ['job_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fresher_salary_min', models.FloatField(default=0)),
                ('fresher_salary_max', models.FloatField(default=0)),
                ('mid_salary_min', models.FloatField(default=0)),
                ('mid_salary_max', models.FloatField(default=0)),
                ('senior_salary_min', models.FloatField(default=0)),
                ('senior_salary_max', models.FloatField(default=0)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='jobs.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='JobProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_json', models.JSONField(default=list)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='jobs.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='CareerGrowthPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_json', models.JSONField(default=list)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='growth_path', to='jobs.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('usage', models.CharField(blank=True, max_length=500)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='jobs.jobrole')),
            ],
            options={
                'ordering': ['tool_name'],
                'unique_together': {('job', 'tool_name')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=200)),
                ('skill_type', models.CharField(choices=[('technical', 'Technical Skill'), ('soft', 'Soft Skill'), ('certification', 'Certification')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobs.jobrole')),
            ],
            options={
                'ordering': ['skill_type', 'skill_name'],
                'unique_together': {('job', 'skill_name')},
            },
        ),
    ]
